Spatial Node Exaple
luxonis/depthai-ros-examples pull request #3
Opened 2021-05-14 10:13 UTC by luiscastro1995

Hi,

As you suggested, here is my PR. If you could put your fixes here would be great!

2021-05-14 16:14 UTC, saching13 requested changes
The above comments should fix the execution issues.

2021-05-14 16:14 UTC, saching13 commented on depthai_examples/lib/yolov4_spatial_pipeline.cpp
> +    auto xoutDepth = _p.create<dai::node::XLinkOut>();
Remove `xoutDepth` along with any links to that. Since you are not getting it over the USB the stream gets filled.

2021-05-14 16:14 UTC, saching13 commented on depthai_examples/lib/yolov4_spatial_pipeline.cpp
> +    auto xoutBoundingBoxDepthMapping = _p.create<dai::node::XLinkOut>();
`xoutBoundingBoxDepthMapping` too. for the same reason as `xoutDepth`

2021-05-17 09:49 UTC, luiscastro1995 commented
I have just tried your fixes and its working like a charm! Thanks

2021-05-17 23:00 UTC, saching13 approved these changes
Except those small formating LGTM

2021-05-17 23:00 UTC, saching13 commented on depthai_examples/lib/yolov4_spatial_pipeline.cpp
> +// }
Can you remove this ?

2021-05-17 23:00 UTC, saching13 commented on depthai_examples/include/depthai_examples/yolov4_spatial_pipeline.hpp
> +};
add an extra line here just to be safe

2021-05-25 18:13 UTC, merged